export type DialectSeed = {
  code: string;
  languageCode: string;
  nameEn: string;
  nameNative?: string;
  region?: string;
  cueTerms: string[];
  notes?: string;
};

/**
 * African + related dialect seeds — curated priority varieties plus catalog ethnic/locale variants.
 */
export const DIALECT_SEEDS: DialectSeed[] = [
  {
    code: 'aa-dj-djibouti-afar',
    languageCode: 'aa',
    nameEn: 'Djibouti Afar (Djibouti)',
    nameNative: 'Djibouti Afar',
    region: 'DJ',
    cueTerms: ["djibouti"],
    notes: 'Ethnic/locale variety from Africa catalog — Djibouti.',
  },
  {
    code: 'ak-gh-akuapem-twi',
    languageCode: 'ak',
    nameEn: 'Akuapem Twi (Ghana)',
    nameNative: 'Akuapem Twi',
    region: 'GH',
    cueTerms: ["akuapem"],
    notes: 'Ethnic/locale variety from Africa catalog — Ghana.',
  },
  {
    code: 'ak-gh-asante',
    languageCode: 'ak',
    nameEn: 'Asante Twi',
    nameNative: 'Asante Twi',
    region: 'GH',
    cueTerms: ["medaase","akwaaba","ɛte sɛn"],
    notes: 'Default Twi variety for Lugemi demos.',
  },
  {
    code: 'ak-gh-asante-twi',
    languageCode: 'ak',
    nameEn: 'Asante Twi (Ghana)',
    nameNative: 'Asante Twi',
    region: 'GH',
    cueTerms: ["asante"],
    notes: 'Ethnic/locale variety from Africa catalog — Ghana.',
  },
  {
    code: 'ak-gh-fante',
    languageCode: 'ak',
    nameEn: 'Fante',
    nameNative: 'Mfantse',
    region: 'GH',
    cueTerms: ["medaase","akwaaba"],
    notes: 'Fante Akan variety.',
  },
  {
    code: 'am-et',
    languageCode: 'am',
    nameEn: 'Ethiopian Amharic',
    nameNative: 'አማርኛ',
    region: 'ET',
    cueTerms: ["ሰላም","አመሰግናለሁ","እባክህ"],
    notes: 'Ethiopic-script cues.',
  },
  {
    code: 'am-et-addis',
    languageCode: 'am',
    nameEn: 'Addis (Ethiopia)',
    nameNative: 'Addis',
    region: 'ET',
    cueTerms: ["addis"],
    notes: 'Ethnic/locale variety from Africa catalog — Ethiopia.',
  },
  {
    code: 'am-et-gojjam',
    languageCode: 'am',
    nameEn: 'Gojjam (Ethiopia)',
    nameNative: 'Gojjam',
    region: 'ET',
    cueTerms: ["gojjam"],
    notes: 'Ethnic/locale variety from Africa catalog — Ethiopia.',
  },
  {
    code: 'am-et-wollo',
    languageCode: 'am',
    nameEn: 'Wollo (Ethiopia)',
    nameNative: 'Wollo',
    region: 'ET',
    cueTerms: ["wollo"],
    notes: 'Ethnic/locale variety from Africa catalog — Ethiopia.',
  },
  {
    code: 'ar-dz-algerian-arabic',
    languageCode: 'ar',
    nameEn: 'Algerian Arabic (Algeria)',
    nameNative: 'Algerian Arabic',
    region: 'DZ',
    cueTerms: ["algerian"],
    notes: 'Ethnic/locale variety from Africa catalog — Algeria.',
  },
  {
    code: 'ar-eg',
    languageCode: 'ar',
    nameEn: 'Egyptian Arabic',
    nameNative: 'مصري',
    region: 'EG',
    cueTerms: ["ازيك","كده","مش","علشان","يعني"],
    notes: 'Colloquial Egyptian.',
  },
  {
    code: 'ar-eg-cairene',
    languageCode: 'ar',
    nameEn: 'Cairene (Egypt)',
    nameNative: 'Cairene',
    region: 'EG',
    cueTerms: ["cairene"],
    notes: 'Ethnic/locale variety from Africa catalog — Egypt.',
  },
  {
    code: 'ar-eg-sa-idi',
    languageCode: 'ar',
    nameEn: 'Sa\'idi (Egypt)',
    nameNative: 'Sa\'idi',
    region: 'EG',
    cueTerms: ["sa'idi"],
    notes: 'Ethnic/locale variety from Africa catalog — Egypt.',
  },
  {
    code: 'ar-ma',
    languageCode: 'ar',
    nameEn: 'Moroccan Darija',
    nameNative: 'الدارجة',
    region: 'MA',
    cueTerms: ["واش","بزاف","فين","صافي","كيفاش"],
    notes: 'Maghrebi cues.',
  },
  {
    code: 'ber-dz-chaoui',
    languageCode: 'ber',
    nameEn: 'Chaoui (Algeria)',
    nameNative: 'Chaoui',
    region: 'DZ',
    cueTerms: ["chaoui"],
    notes: 'Ethnic/locale variety from Africa catalog — Algeria.',
  },
  {
    code: 'ber-dz-kabyle',
    languageCode: 'ber',
    nameEn: 'Kabyle (Algeria)',
    nameNative: 'Kabyle',
    region: 'DZ',
    cueTerms: ["kabyle"],
    notes: 'Ethnic/locale variety from Africa catalog — Algeria.',
  },
  {
    code: 'ber-dz-mzab',
    languageCode: 'ber',
    nameEn: 'Mzab (Algeria)',
    nameNative: 'Mzab',
    region: 'DZ',
    cueTerms: ["mzab"],
    notes: 'Ethnic/locale variety from Africa catalog — Algeria.',
  },
  {
    code: 'bm-ml-bamako',
    languageCode: 'bm',
    nameEn: 'Bamako (Mali)',
    nameNative: 'Bamako',
    region: 'ML',
    cueTerms: ["bamako"],
    notes: 'Ethnic/locale variety from Africa catalog — Mali.',
  },
  {
    code: 'cop-eg-bohairic',
    languageCode: 'cop',
    nameEn: 'Bohairic (Egypt)',
    nameNative: 'Bohairic',
    region: 'EG',
    cueTerms: ["bohairic"],
    notes: 'Ethnic/locale variety from Africa catalog — Egypt.',
  },
  {
    code: 'din-ss-padang',
    languageCode: 'din',
    nameEn: 'Padang (South Sudan)',
    nameNative: 'Padang',
    region: 'SS',
    cueTerms: ["padang"],
    notes: 'Ethnic/locale variety from Africa catalog — South Sudan.',
  },
  {
    code: 'din-ss-rek',
    languageCode: 'din',
    nameEn: 'Rek (South Sudan)',
    nameNative: 'Rek',
    region: 'SS',
    cueTerms: ["rek"],
    notes: 'Ethnic/locale variety from Africa catalog — South Sudan.',
  },
  {
    code: 'dyu-bf-dyula',
    languageCode: 'dyu',
    nameEn: 'Dyula (Burkina Faso)',
    nameNative: 'Dyula',
    region: 'BF',
    cueTerms: ["dyula"],
    notes: 'Ethnic/locale variety from Africa catalog — Burkina Faso.',
  },
  {
    code: 'ee-gh-anlo',
    languageCode: 'ee',
    nameEn: 'Anlo (Ghana)',
    nameNative: 'Anlo',
    region: 'GH',
    cueTerms: ["anlo"],
    notes: 'Ethnic/locale variety from Africa catalog — Ghana.',
  },
  {
    code: 'ee-gh-tongu',
    languageCode: 'ee',
    nameEn: 'Tongu (Ghana)',
    nameNative: 'Tongu',
    region: 'GH',
    cueTerms: ["tongu"],
    notes: 'Ethnic/locale variety from Africa catalog — Ghana.',
  },
  {
    code: 'en-bw-botswana-english',
    languageCode: 'en',
    nameEn: 'Botswana English (Botswana)',
    nameNative: 'Botswana English',
    region: 'BW',
    cueTerms: ["botswana"],
    notes: 'Ethnic/locale variety from Africa catalog — Botswana.',
  },
  {
    code: 'en-cm-cameroonian-pidgin',
    languageCode: 'en',
    nameEn: 'Cameroonian Pidgin (Cameroon)',
    nameNative: 'Cameroonian Pidgin',
    region: 'CM',
    cueTerms: ["cameroonian"],
    notes: 'Ethnic/locale variety from Africa catalog — Cameroon.',
  },
  {
    code: 'en-gh-ghanaian-english',
    languageCode: 'en',
    nameEn: 'Ghanaian English (Ghana)',
    nameNative: 'Ghanaian English',
    region: 'GH',
    cueTerms: ["ghanaian"],
    notes: 'Ethnic/locale variety from Africa catalog — Ghana.',
  },
  {
    code: 'en-ng',
    languageCode: 'en',
    nameEn: 'Nigerian English',
    region: 'NG',
    cueTerms: ["abi","na wa","how far","oya","wetin"],
    notes: 'Lexical cues only.',
  },
  {
    code: 'en-za',
    languageCode: 'en',
    nameEn: 'South African English',
    region: 'ZA',
    cueTerms: ["lekker","braai","robot","just now","howzit"],
    notes: 'Lexical cues only.',
  },
  {
    code: 'es-gq-equatoguinean-spanish',
    languageCode: 'es',
    nameEn: 'Equatoguinean Spanish (Equatorial Guinea)',
    nameNative: 'Equatoguinean Spanish',
    region: 'GQ',
    cueTerms: ["equatoguinean"],
    notes: 'Ethnic/locale variety from Africa catalog — Equatorial Guinea.',
  },
  {
    code: 'es-ma-northern',
    languageCode: 'es',
    nameEn: 'Northern (Morocco)',
    nameNative: 'Northern',
    region: 'MA',
    cueTerms: ["northern"],
    notes: 'Ethnic/locale variety from Africa catalog — Morocco.',
  },
  {
    code: 'ff-bf-gurma-fula',
    languageCode: 'ff',
    nameEn: 'Gurma Fula (Burkina Faso)',
    nameNative: 'Gurma Fula',
    region: 'BF',
    cueTerms: ["gurma"],
    notes: 'Ethnic/locale variety from Africa catalog — Burkina Faso.',
  },
  {
    code: 'ff-cm-adamawa',
    languageCode: 'ff',
    nameEn: 'Adamawa (Cameroon)',
    nameNative: 'Adamawa',
    region: 'CM',
    cueTerms: ["adamawa"],
    notes: 'Ethnic/locale variety from Africa catalog — Cameroon.',
  },
  {
    code: 'ff-gn-futa-jalon',
    languageCode: 'ff',
    nameEn: 'Futa Jalon (Guinea)',
    nameNative: 'Futa Jalon',
    region: 'GN',
    cueTerms: ["futa"],
    notes: 'Ethnic/locale variety from Africa catalog — Guinea.',
  },
  {
    code: 'fon-bj-abomey',
    languageCode: 'fon',
    nameEn: 'Abomey (Benin)',
    nameNative: 'Abomey',
    region: 'BJ',
    cueTerms: ["abomey"],
    notes: 'Ethnic/locale variety from Africa catalog — Benin.',
  },
  {
    code: 'fon-bj-ouidah',
    languageCode: 'fon',
    nameEn: 'Ouidah (Benin)',
    nameNative: 'Ouidah',
    region: 'BJ',
    cueTerms: ["ouidah"],
    notes: 'Ethnic/locale variety from Africa catalog — Benin.',
  },
  {
    code: 'fr-bj-beninese-french',
    languageCode: 'fr',
    nameEn: 'Beninese French (Benin)',
    nameNative: 'Beninese French',
    region: 'BJ',
    cueTerms: ["beninese"],
    notes: 'Ethnic/locale variety from Africa catalog — Benin.',
  },
  {
    code: 'fr-cd-congolese-french',
    languageCode: 'fr',
    nameEn: 'Congolese French (DR Congo)',
    nameNative: 'Congolese French',
    region: 'CD',
    cueTerms: ["congolese"],
    notes: 'Ethnic/locale variety from Africa catalog — DR Congo.',
  },
  {
    code: 'fr-ci-ivorian-french',
    languageCode: 'fr',
    nameEn: 'Ivorian French (Côte d\'Ivoire)',
    nameNative: 'Ivorian French',
    region: 'CI',
    cueTerms: ["ivorian"],
    notes: 'Ethnic/locale variety from Africa catalog — Côte d\'Ivoire.',
  },
  {
    code: 'gez-et-liturgical',
    languageCode: 'gez',
    nameEn: 'Liturgical (Ethiopia)',
    nameNative: 'Liturgical',
    region: 'ET',
    cueTerms: ["liturgical"],
    notes: 'Ethnic/locale variety from Africa catalog — Ethiopia.',
  },
  {
    code: 'ha-ne-niger-hausa',
    languageCode: 'ha',
    nameEn: 'Niger Hausa (Niger)',
    nameNative: 'Niger Hausa',
    region: 'NE',
    cueTerms: ["niger"],
    notes: 'Ethnic/locale variety from Africa catalog — Niger.',
  },
  {
    code: 'ha-ng',
    languageCode: 'ha',
    nameEn: 'Nigerian Hausa',
    nameNative: 'Hausa',
    region: 'NG',
    cueTerms: ["sannu","na gode","yaya","ina kwana"],
    notes: 'Common greeting cues.',
  },
  {
    code: 'ha-ng-kano',
    languageCode: 'ha',
    nameEn: 'Kano (Nigeria)',
    nameNative: 'Kano',
    region: 'NG',
    cueTerms: ["kano"],
    notes: 'Ethnic/locale variety from Africa catalog — Nigeria.',
  },
  {
    code: 'ha-ng-katsina',
    languageCode: 'ha',
    nameEn: 'Katsina (Nigeria)',
    nameNative: 'Katsina',
    region: 'NG',
    cueTerms: ["katsina"],
    notes: 'Ethnic/locale variety from Africa catalog — Nigeria.',
  },
  {
    code: 'ig-ng-central',
    languageCode: 'ig',
    nameEn: 'Central (Nigeria)',
    nameNative: 'Central',
    region: 'NG',
    cueTerms: ["central"],
    notes: 'Ethnic/locale variety from Africa catalog — Nigeria.',
  },
  {
    code: 'ig-ng-onitsha',
    languageCode: 'ig',
    nameEn: 'Onitsha (Nigeria)',
    nameNative: 'Onitsha',
    region: 'NG',
    cueTerms: ["onitsha"],
    notes: 'Ethnic/locale variety from Africa catalog — Nigeria.',
  },
  {
    code: 'ig-ng-owerri',
    languageCode: 'ig',
    nameEn: 'Owerri (Nigeria)',
    nameNative: 'Owerri',
    region: 'NG',
    cueTerms: ["owerri"],
    notes: 'Ethnic/locale variety from Africa catalog — Nigeria.',
  },
  {
    code: 'kea-cv-s-o-vicente',
    languageCode: 'kea',
    nameEn: 'São Vicente (Cabo Verde)',
    nameNative: 'São Vicente',
    region: 'CV',
    cueTerms: ["são"],
    notes: 'Ethnic/locale variety from Africa catalog — Cabo Verde.',
  },
  {
    code: 'kea-cv-santiago',
    languageCode: 'kea',
    nameEn: 'Santiago (Cabo Verde)',
    nameNative: 'Santiago',
    region: 'CV',
    cueTerms: ["santiago"],
    notes: 'Ethnic/locale variety from Africa catalog — Cabo Verde.',
  },
  {
    code: 'kj-ao-kuanyama',
    languageCode: 'kj',
    nameEn: 'Kuanyama (Angola)',
    nameNative: 'Kuanyama',
    region: 'AO',
    cueTerms: ["kuanyama"],
    notes: 'Ethnic/locale variety from Africa catalog — Angola.',
  },
  {
    code: 'kj-na-kwanyama',
    languageCode: 'kj',
    nameEn: 'Kwanyama (Namibia)',
    nameNative: 'Kwanyama',
    region: 'NA',
    cueTerms: ["kwanyama"],
    notes: 'Ethnic/locale variety from Africa catalog — Namibia.',
  },
  {
    code: 'kj-na-ndonga',
    languageCode: 'kj',
    nameEn: 'Ndonga (Namibia)',
    nameNative: 'Ndonga',
    region: 'NA',
    cueTerms: ["ndonga"],
    notes: 'Ethnic/locale variety from Africa catalog — Namibia.',
  },
  {
    code: 'kln-ke-kipsigis',
    languageCode: 'kln',
    nameEn: 'Kipsigis (Kenya)',
    nameNative: 'Kipsigis',
    region: 'KE',
    cueTerms: ["kipsigis"],
    notes: 'Ethnic/locale variety from Africa catalog — Kenya.',
  },
  {
    code: 'kln-ke-nandi',
    languageCode: 'kln',
    nameEn: 'Nandi (Kenya)',
    nameNative: 'Nandi',
    region: 'KE',
    cueTerms: ["nandi"],
    notes: 'Ethnic/locale variety from Africa catalog — Kenya.',
  },
  {
    code: 'kmb-ao-luanda',
    languageCode: 'kmb',
    nameEn: 'Luanda (Angola)',
    nameNative: 'Luanda',
    region: 'AO',
    cueTerms: ["luanda"],
    notes: 'Ethnic/locale variety from Africa catalog — Angola.',
  },
  {
    code: 'kri-sl-freetown',
    languageCode: 'kri',
    nameEn: 'Freetown (Sierra Leone)',
    nameNative: 'Freetown',
    region: 'SL',
    cueTerms: ["freetown"],
    notes: 'Ethnic/locale variety from Africa catalog — Sierra Leone.',
  },
  {
    code: 'lg-ug-central',
    languageCode: 'lg',
    nameEn: 'Central (Uganda)',
    nameNative: 'Central',
    region: 'UG',
    cueTerms: ["central"],
    notes: 'Ethnic/locale variety from Africa catalog — Uganda.',
  },
  {
    code: 'ln-cd-kinshasa',
    languageCode: 'ln',
    nameEn: 'Kinshasa (DR Congo)',
    nameNative: 'Kinshasa',
    region: 'CD',
    cueTerms: ["kinshasa"],
    notes: 'Ethnic/locale variety from Africa catalog — DR Congo.',
  },
  {
    code: 'ln-cg-brazzaville',
    languageCode: 'ln',
    nameEn: 'Brazzaville (Congo)',
    nameNative: 'Brazzaville',
    region: 'CG',
    cueTerms: ["brazzaville"],
    notes: 'Ethnic/locale variety from Africa catalog — Congo.',
  },
  {
    code: 'mg-mg-betsimisaraka',
    languageCode: 'mg',
    nameEn: 'Betsimisaraka (Madagascar)',
    nameNative: 'Betsimisaraka',
    region: 'MG',
    cueTerms: ["betsimisaraka"],
    notes: 'Ethnic/locale variety from Africa catalog — Madagascar.',
  },
  {
    code: 'mg-mg-merina',
    languageCode: 'mg',
    nameEn: 'Merina (Madagascar)',
    nameNative: 'Merina',
    region: 'MG',
    cueTerms: ["merina"],
    notes: 'Ethnic/locale variety from Africa catalog — Madagascar.',
  },
  {
    code: 'mg-mg-sakalava',
    languageCode: 'mg',
    nameEn: 'Sakalava (Madagascar)',
    nameNative: 'Sakalava',
    region: 'MG',
    cueTerms: ["sakalava"],
    notes: 'Ethnic/locale variety from Africa catalog — Madagascar.',
  },
  {
    code: 'mos-bf-central-moore',
    languageCode: 'mos',
    nameEn: 'Central Moore (Burkina Faso)',
    nameNative: 'Central Moore',
    region: 'BF',
    cueTerms: ["central"],
    notes: 'Ethnic/locale variety from Africa catalog — Burkina Faso.',
  },
  {
    code: 'nub-eg-kenzi',
    languageCode: 'nub',
    nameEn: 'Kenzi (Egypt)',
    nameNative: 'Kenzi',
    region: 'EG',
    cueTerms: ["kenzi"],
    notes: 'Ethnic/locale variety from Africa catalog — Egypt.',
  },
  {
    code: 'nub-eg-nobiin',
    languageCode: 'nub',
    nameEn: 'Nobiin (Egypt)',
    nameNative: 'Nobiin',
    region: 'EG',
    cueTerms: ["nobiin"],
    notes: 'Ethnic/locale variety from Africa catalog — Egypt.',
  },
  {
    code: 'ny-mw-central',
    languageCode: 'ny',
    nameEn: 'Central (Malawi)',
    nameNative: 'Central',
    region: 'MW',
    cueTerms: ["central"],
    notes: 'Ethnic/locale variety from Africa catalog — Malawi.',
  },
  {
    code: 'om-et-borana',
    languageCode: 'om',
    nameEn: 'Borana (Ethiopia)',
    nameNative: 'Borana',
    region: 'ET',
    cueTerms: ["borana"],
    notes: 'Ethnic/locale variety from Africa catalog — Ethiopia.',
  },
  {
    code: 'om-et-mecha',
    languageCode: 'om',
    nameEn: 'Mecha (Ethiopia)',
    nameNative: 'Mecha',
    region: 'ET',
    cueTerms: ["mecha"],
    notes: 'Ethnic/locale variety from Africa catalog — Ethiopia.',
  },
  {
    code: 'om-et-tulama',
    languageCode: 'om',
    nameEn: 'Tulama (Ethiopia)',
    nameNative: 'Tulama',
    region: 'ET',
    cueTerms: ["tulama"],
    notes: 'Ethnic/locale variety from Africa catalog — Ethiopia.',
  },
  {
    code: 'pcm-ng-lagos',
    languageCode: 'pcm',
    nameEn: 'Lagos (Nigeria)',
    nameNative: 'Lagos',
    region: 'NG',
    cueTerms: ["lagos"],
    notes: 'Ethnic/locale variety from Africa catalog — Nigeria.',
  },
  {
    code: 'pcm-ng-warri',
    languageCode: 'pcm',
    nameEn: 'Warri (Nigeria)',
    nameNative: 'Warri',
    region: 'NG',
    cueTerms: ["warri"],
    notes: 'Ethnic/locale variety from Africa catalog — Nigeria.',
  },
  {
    code: 'pt-ao-angolan-portuguese',
    languageCode: 'pt',
    nameEn: 'Angolan Portuguese (Angola)',
    nameNative: 'Angolan Portuguese',
    region: 'AO',
    cueTerms: ["angolan"],
    notes: 'Ethnic/locale variety from Africa catalog — Angola.',
  },
  {
    code: 'pt-mz-mozambican-portuguese',
    languageCode: 'pt',
    nameEn: 'Mozambican Portuguese (Mozambique)',
    nameNative: 'Mozambican Portuguese',
    region: 'MZ',
    cueTerms: ["mozambican"],
    notes: 'Ethnic/locale variety from Africa catalog — Mozambique.',
  },
  {
    code: 'rn-bi-standard-kirundi',
    languageCode: 'rn',
    nameEn: 'Standard Kirundi (Burundi)',
    nameNative: 'Standard Kirundi',
    region: 'BI',
    cueTerms: ["standard"],
    notes: 'Ethnic/locale variety from Africa catalog — Burundi.',
  },
  {
    code: 'rw-rw-standard',
    languageCode: 'rw',
    nameEn: 'Standard (Rwanda)',
    nameNative: 'Standard',
    region: 'RW',
    cueTerms: ["standard"],
    notes: 'Ethnic/locale variety from Africa catalog — Rwanda.',
  },
  {
    code: 'sar-td-ngambay',
    languageCode: 'sar',
    nameEn: 'Ngambay (Chad)',
    nameNative: 'Ngambay',
    region: 'TD',
    cueTerms: ["ngambay"],
    notes: 'Ethnic/locale variety from Africa catalog — Chad.',
  },
  {
    code: 'sg-cf-bangui-sango',
    languageCode: 'sg',
    nameEn: 'Bangui Sango (Central African Republic)',
    nameNative: 'Bangui Sango',
    region: 'CF',
    cueTerms: ["bangui"],
    notes: 'Ethnic/locale variety from Africa catalog — Central African Republic.',
  },
  {
    code: 'sn-zw-karanga',
    languageCode: 'sn',
    nameEn: 'Karanga (Zimbabwe)',
    nameNative: 'Karanga',
    region: 'ZW',
    cueTerms: ["karanga"],
    notes: 'Ethnic/locale variety from Africa catalog — Zimbabwe.',
  },
  {
    code: 'sn-zw-manyika',
    languageCode: 'sn',
    nameEn: 'Manyika (Zimbabwe)',
    nameNative: 'Manyika',
    region: 'ZW',
    cueTerms: ["manyika"],
    notes: 'Ethnic/locale variety from Africa catalog — Zimbabwe.',
  },
  {
    code: 'sn-zw-zezuru',
    languageCode: 'sn',
    nameEn: 'Zezuru (Zimbabwe)',
    nameNative: 'Zezuru',
    region: 'ZW',
    cueTerms: ["zezuru"],
    notes: 'Ethnic/locale variety from Africa catalog — Zimbabwe.',
  },
  {
    code: 'so-dj-northern',
    languageCode: 'so',
    nameEn: 'Northern (Djibouti)',
    nameNative: 'Northern',
    region: 'DJ',
    cueTerms: ["northern"],
    notes: 'Ethnic/locale variety from Africa catalog — Djibouti.',
  },
  {
    code: 'so-so-benadir',
    languageCode: 'so',
    nameEn: 'Benadir (Somalia)',
    nameNative: 'Benadir',
    region: 'SO',
    cueTerms: ["benadir"],
    notes: 'Ethnic/locale variety from Africa catalog — Somalia.',
  },
  {
    code: 'so-so-maay',
    languageCode: 'so',
    nameEn: 'Maay (Somalia)',
    nameNative: 'Maay',
    region: 'SO',
    cueTerms: ["maay"],
    notes: 'Ethnic/locale variety from Africa catalog — Somalia.',
  },
  {
    code: 'ss-sz-standard-swati',
    languageCode: 'ss',
    nameEn: 'Standard Swati (Eswatini)',
    nameNative: 'Standard Swati',
    region: 'SZ',
    cueTerms: ["standard"],
    notes: 'Ethnic/locale variety from Africa catalog — Eswatini.',
  },
  {
    code: 'st-ls-lesotho-sesotho',
    languageCode: 'st',
    nameEn: 'Lesotho Sesotho (Lesotho)',
    nameNative: 'Lesotho Sesotho',
    region: 'LS',
    cueTerms: ["lesotho"],
    notes: 'Ethnic/locale variety from Africa catalog — Lesotho.',
  },
  {
    code: 'sw-bi-burundi-swahili',
    languageCode: 'sw',
    nameEn: 'Burundi Swahili (Burundi)',
    nameNative: 'Burundi Swahili',
    region: 'BI',
    cueTerms: ["burundi"],
    notes: 'Ethnic/locale variety from Africa catalog — Burundi.',
  },
  {
    code: 'sw-cd-congo-swahili',
    languageCode: 'sw',
    nameEn: 'Congo Swahili (DR Congo)',
    nameNative: 'Congo Swahili',
    region: 'CD',
    cueTerms: ["congo"],
    notes: 'Ethnic/locale variety from Africa catalog — DR Congo.',
  },
  {
    code: 'sw-ke',
    languageCode: 'sw',
    nameEn: 'Kenyan Swahili',
    nameNative: 'Kiswahili cha Kenya',
    region: 'KE',
    cueTerms: ["sasa","poa","niaje","bro","uko aje","safi"],
    notes: 'Urban Kenyan cues.',
  },
  {
    code: 'sw-ke-kenyan-swahili',
    languageCode: 'sw',
    nameEn: 'Kenyan Swahili (Kenya)',
    nameNative: 'Kenyan Swahili',
    region: 'KE',
    cueTerms: ["kenyan"],
    notes: 'Ethnic/locale variety from Africa catalog — Kenya.',
  },
  {
    code: 'sw-tz',
    languageCode: 'sw',
    nameEn: 'Tanzanian / coastal Swahili',
    nameNative: 'Kiswahili cha pwani',
    region: 'TZ',
    cueTerms: ["sana","kwenye","labda","tafadhali","asante sana"],
    notes: 'Standard coastal-leaning cues.',
  },
  {
    code: 'ti-er-asmara',
    languageCode: 'ti',
    nameEn: 'Asmara (Eritrea)',
    nameNative: 'Asmara',
    region: 'ER',
    cueTerms: ["asmara"],
    notes: 'Ethnic/locale variety from Africa catalog — Eritrea.',
  },
  {
    code: 'tn-bw-kwena',
    languageCode: 'tn',
    nameEn: 'Kwena (Botswana)',
    nameNative: 'Kwena',
    region: 'BW',
    cueTerms: ["kwena"],
    notes: 'Ethnic/locale variety from Africa catalog — Botswana.',
  },
  {
    code: 'tn-bw-ngwato',
    languageCode: 'tn',
    nameEn: 'Ngwato (Botswana)',
    nameNative: 'Ngwato',
    region: 'BW',
    cueTerms: ["ngwato"],
    notes: 'Ethnic/locale variety from Africa catalog — Botswana.',
  },
  {
    code: 'umb-ao-central-umbundu',
    languageCode: 'umb',
    nameEn: 'Central Umbundu (Angola)',
    nameNative: 'Central Umbundu',
    region: 'AO',
    cueTerms: ["central"],
    notes: 'Ethnic/locale variety from Africa catalog — Angola.',
  },
  {
    code: 'wo-gm-gambian-wolof',
    languageCode: 'wo',
    nameEn: 'Gambian Wolof (Gambia)',
    nameNative: 'Gambian Wolof',
    region: 'GM',
    cueTerms: ["gambian"],
    notes: 'Ethnic/locale variety from Africa catalog — Gambia.',
  },
  {
    code: 'wo-sn-dakar',
    languageCode: 'wo',
    nameEn: 'Dakar (Senegal)',
    nameNative: 'Dakar',
    region: 'SN',
    cueTerms: ["dakar"],
    notes: 'Ethnic/locale variety from Africa catalog — Senegal.',
  },
  {
    code: 'xh-za-isixhosa',
    languageCode: 'xh',
    nameEn: 'isiXhosa (South Africa)',
    nameNative: 'isiXhosa',
    region: 'ZA',
    cueTerms: ["isixhosa"],
    notes: 'Ethnic/locale variety from Africa catalog — South Africa.',
  },
  {
    code: 'yo-bj-anago',
    languageCode: 'yo',
    nameEn: 'Anago (Benin)',
    nameNative: 'Anago',
    region: 'BJ',
    cueTerms: ["anago"],
    notes: 'Ethnic/locale variety from Africa catalog — Benin.',
  },
  {
    code: 'yo-ng',
    languageCode: 'yo',
    nameEn: 'Nigerian Yoruba',
    nameNative: 'Yorùbá',
    region: 'NG',
    cueTerms: ["ẹ káàárọ̀","ẹ kú","ọmọ","jọ̀ọ́","béẹ̀ni"],
    notes: 'Common orthographic forms.',
  },
  {
    code: 'yo-ng-egba',
    languageCode: 'yo',
    nameEn: 'Egba (Nigeria)',
    nameNative: 'Egba',
    region: 'NG',
    cueTerms: ["egba"],
    notes: 'Ethnic/locale variety from Africa catalog — Nigeria.',
  },
  {
    code: 'yo-ng-ijebu',
    languageCode: 'yo',
    nameEn: 'Ijebu (Nigeria)',
    nameNative: 'Ijebu',
    region: 'NG',
    cueTerms: ["ijebu"],
    notes: 'Ethnic/locale variety from Africa catalog — Nigeria.',
  },
  {
    code: 'zdj-km-shimwali',
    languageCode: 'zdj',
    nameEn: 'Shimwali (Comoros)',
    nameNative: 'Shimwali',
    region: 'KM',
    cueTerms: ["shimwali"],
    notes: 'Ethnic/locale variety from Africa catalog — Comoros.',
  },
  {
    code: 'zdj-km-shingazidja',
    languageCode: 'zdj',
    nameEn: 'Shingazidja (Comoros)',
    nameNative: 'Shingazidja',
    region: 'KM',
    cueTerms: ["shingazidja"],
    notes: 'Ethnic/locale variety from Africa catalog — Comoros.',
  },
  {
    code: 'zdj-km-shinzwani',
    languageCode: 'zdj',
    nameEn: 'Shinzwani (Comoros)',
    nameNative: 'Shinzwani',
    region: 'KM',
    cueTerms: ["shinzwani"],
    notes: 'Ethnic/locale variety from Africa catalog — Comoros.',
  },
  {
    code: 'zgh-ma-central-atlas',
    languageCode: 'zgh',
    nameEn: 'Central Atlas (Morocco)',
    nameNative: 'Central Atlas',
    region: 'MA',
    cueTerms: ["central"],
    notes: 'Ethnic/locale variety from Africa catalog — Morocco.',
  },
  {
    code: 'zgh-ma-tachelhit',
    languageCode: 'zgh',
    nameEn: 'Tachelhit (Morocco)',
    nameNative: 'Tachelhit',
    region: 'MA',
    cueTerms: ["tachelhit"],
    notes: 'Ethnic/locale variety from Africa catalog — Morocco.',
  },
  {
    code: 'zgh-ma-tarifit',
    languageCode: 'zgh',
    nameEn: 'Tarifit (Morocco)',
    nameNative: 'Tarifit',
    region: 'MA',
    cueTerms: ["tarifit"],
    notes: 'Ethnic/locale variety from Africa catalog — Morocco.',
  },
  {
    code: 'zu-za',
    languageCode: 'zu',
    nameEn: 'South African Zulu',
    nameNative: 'isiZulu',
    region: 'ZA',
    cueTerms: ["sawubona","ngiyabonga","unjani","yebo"],
    notes: 'Common greeting cues.',
  },
  {
    code: 'zu-za-standard-zulu',
    languageCode: 'zu',
    nameEn: 'Standard Zulu (South Africa)',
    nameNative: 'Standard Zulu',
    region: 'ZA',
    cueTerms: ["standard"],
    notes: 'Ethnic/locale variety from Africa catalog — South Africa.',
  },

  {
    code: 'th-th-central',
    languageCode: 'th',
    nameEn: 'Central Thai',
    nameNative: 'Central Thai',
    region: 'TH',
    cueTerms: ["khráp"],
    notes: 'Regional registry dialect for TH.',
  },
  {
    code: 'th-th-isan',
    languageCode: 'th',
    nameEn: 'Isan Thai',
    nameNative: 'Isan Thai',
    region: 'TH',
    cueTerms: ["isan"],
    notes: 'Regional registry dialect for TH.',
  },
  {
    code: 'vi-vn-hanoi',
    languageCode: 'vi',
    nameEn: 'Hanoi Vietnamese',
    nameNative: 'Hanoi Vietnamese',
    region: 'VN',
    cueTerms: ["a", "nhe"],
    notes: 'Regional registry dialect for VN.',
  },
  {
    code: 'vi-vn-saigon',
    languageCode: 'vi',
    nameEn: 'Saigon Vietnamese',
    nameNative: 'Saigon Vietnamese',
    region: 'VN',
    cueTerms: ["nha"],
    notes: 'Regional registry dialect for VN.',
  },
  {
    code: 'ms-my-standard',
    languageCode: 'ms',
    nameEn: 'Standard Malay',
    nameNative: 'Standard Malay',
    region: 'MY',
    cueTerms: ["terima kasih"],
    notes: 'Regional registry dialect for MY.',
  },
  {
    code: 'fil-ph-manila',
    languageCode: 'fil',
    nameEn: 'Manila Filipino',
    nameNative: 'Manila Filipino',
    region: 'PH',
    cueTerms: ["po", "opo"],
    notes: 'Regional registry dialect for PH.',
  },
  {
    code: 'tl-ph-manila',
    languageCode: 'tl',
    nameEn: 'Manila Tagalog',
    nameNative: 'Manila Tagalog',
    region: 'PH',
    cueTerms: ["po"],
    notes: 'Regional registry dialect for PH.',
  },
  {
    code: 'km-kh-phnom-penh',
    languageCode: 'km',
    nameEn: 'Phnom Penh Khmer',
    nameNative: 'Phnom Penh Khmer',
    region: 'KH',
    cueTerms: ["orkun"],
    notes: 'Regional registry dialect for KH.',
  },
  {
    code: 'lo-la-vientiane',
    languageCode: 'lo',
    nameEn: 'Vientiane Lao',
    nameNative: 'Vientiane Lao',
    region: 'LA',
    cueTerms: ["khop jai"],
    notes: 'Regional registry dialect for LA.',
  },
  {
    code: 'my-mm-yangon',
    languageCode: 'my',
    nameEn: 'Yangon Burmese',
    nameNative: 'Yangon Burmese',
    region: 'MM',
    cueTerms: ["kyeizu tin ba de"],
    notes: 'Regional registry dialect for MM.',
  },
  {
    code: 'jv-id-central',
    languageCode: 'jv',
    nameEn: 'Central Javanese',
    nameNative: 'Central Javanese',
    region: 'ID',
    cueTerms: ["matur nuwun"],
    notes: 'Regional registry dialect for ID.',
  },
  {
    code: 'su-id-priangan',
    languageCode: 'su',
    nameEn: 'Priangan Sundanese',
    nameNative: 'Priangan Sundanese',
    region: 'ID',
    cueTerms: ["hatur nuhun"],
    notes: 'Regional registry dialect for ID.',
  },
  {
    code: 'ceb-ph-cebu',
    languageCode: 'ceb',
    nameEn: 'Cebu City Cebuano',
    nameNative: 'Cebu City Cebuano',
    region: 'PH',
    cueTerms: ["salamat"],
    notes: 'Regional registry dialect for PH.',
  },
  {
    code: 'tet-tl-dili',
    languageCode: 'tet',
    nameEn: 'Dili Tetum',
    nameNative: 'Dili Tetum',
    region: 'TL',
    cueTerms: ["obrigadu"],
    notes: 'Regional registry dialect for TL.',
  },
  {
    code: 'fa-ir-tehran',
    languageCode: 'fa',
    nameEn: 'Tehrani Persian',
    nameNative: 'Tehrani Persian',
    region: 'IR',
    cueTerms: ["mersi", "lotfan"],
    notes: 'Regional registry dialect for IR.',
  },
  {
    code: 'he-il-modern',
    languageCode: 'he',
    nameEn: 'Modern Israeli Hebrew',
    nameNative: 'Modern Israeli Hebrew',
    region: 'IL',
    cueTerms: ["shalom", "toda"],
    notes: 'Regional registry dialect for IL.',
  },
  {
    code: 'ur-pk-karachi',
    languageCode: 'ur',
    nameEn: 'Karachi Urdu',
    nameNative: 'Karachi Urdu',
    region: 'PK',
    cueTerms: ["shukriya"],
    notes: 'Regional registry dialect for PK.',
  },
  {
    code: 'ps-af-kabul',
    languageCode: 'ps',
    nameEn: 'Kabul Pashto',
    nameNative: 'Kabul Pashto',
    region: 'AF',
    cueTerms: ["manana"],
    notes: 'Regional registry dialect for AF.',
  },
  {
    code: 'ku-tr-kurmanji',
    languageCode: 'ku',
    nameEn: 'Kurmanji',
    nameNative: 'Kurmanji',
    region: 'TR',
    cueTerms: ["spas"],
    notes: 'Regional registry dialect for TR.',
  },
  {
    code: 'ckb-iq-sorani',
    languageCode: 'ckb',
    nameEn: 'Sorani',
    nameNative: 'Sorani',
    region: 'IQ',
    cueTerms: ["supas"],
    notes: 'Regional registry dialect for IQ.',
  },
  {
    code: 'ar-sa-hijazi',
    languageCode: 'ar',
    nameEn: 'Hijazi Arabic',
    nameNative: 'Hijazi Arabic',
    region: 'SA',
    cueTerms: ["kayfak"],
    notes: 'Regional registry dialect for SA.',
  },
  {
    code: 'ar-ae-gulf',
    languageCode: 'ar',
    nameEn: 'Gulf Arabic',
    nameNative: 'Gulf Arabic',
    region: 'AE',
    cueTerms: ["shu"],
    notes: 'Regional registry dialect for AE.',
  },
  {
    code: 'ar-iq-mesopotamian',
    languageCode: 'ar',
    nameEn: 'Iraqi Arabic',
    nameNative: 'Iraqi Arabic',
    region: 'IQ',
    cueTerms: ["shlonak"],
    notes: 'Regional registry dialect for IQ.',
  },
  {
    code: 'de-de-standard',
    languageCode: 'de',
    nameEn: 'Standard German',
    nameNative: 'Standard German',
    region: 'DE',
    cueTerms: ["bitte", "danke"],
    notes: 'Regional registry dialect for DE.',
  },
  {
    code: 'fr-fr-metropolitan',
    languageCode: 'fr',
    nameEn: 'Metropolitan French',
    nameNative: 'Metropolitan French',
    region: 'FR',
    cueTerms: ["bonjour"],
    notes: 'Regional registry dialect for FR.',
  },
  {
    code: 'es-es-castilian',
    languageCode: 'es',
    nameEn: 'Castilian Spanish',
    nameNative: 'Castilian Spanish',
    region: 'ES',
    cueTerms: ["vale"],
    notes: 'Regional registry dialect for ES.',
  },
  {
    code: 'es-mx-mexican',
    languageCode: 'es',
    nameEn: 'Mexican Spanish',
    nameNative: 'Mexican Spanish',
    region: 'MX',
    cueTerms: ["orale"],
    notes: 'Regional registry dialect for MX.',
  },
  {
    code: 'es-ar-rioplatense',
    languageCode: 'es',
    nameEn: 'Rioplatense Spanish',
    nameNative: 'Rioplatense Spanish',
    region: 'AR',
    cueTerms: ["che"],
    notes: 'Regional registry dialect for AR.',
  },
  {
    code: 'pt-br-brazilian',
    languageCode: 'pt',
    nameEn: 'Brazilian Portuguese',
    nameNative: 'Brazilian Portuguese',
    region: 'BR',
    cueTerms: ["obrigado"],
    notes: 'Regional registry dialect for BR.',
  },
  {
    code: 'pt-pt-european',
    languageCode: 'pt',
    nameEn: 'European Portuguese',
    nameNative: 'European Portuguese',
    region: 'PT',
    cueTerms: ["obrigado"],
    notes: 'Regional registry dialect for PT.',
  },
  {
    code: 'pl-pl-standard',
    languageCode: 'pl',
    nameEn: 'Standard Polish',
    nameNative: 'Standard Polish',
    region: 'PL',
    cueTerms: ["dziekuje"],
    notes: 'Regional registry dialect for PL.',
  },
  {
    code: 'sv-se-standard',
    languageCode: 'sv',
    nameEn: 'Standard Swedish',
    nameNative: 'Standard Swedish',
    region: 'SE',
    cueTerms: ["tack"],
    notes: 'Regional registry dialect for SE.',
  },
  {
    code: 'en-gb-british',
    languageCode: 'en',
    nameEn: 'British English',
    nameNative: 'British English',
    region: 'GB',
    cueTerms: ["cheers", "brilliant"],
    notes: 'Regional registry dialect for GB.',
  },
  {
    code: 'en-us-general-american',
    languageCode: 'en',
    nameEn: 'General American English',
    nameNative: 'General American English',
    region: 'US',
    cueTerms: ["yeah"],
    notes: 'Regional registry dialect for US.',
  },
  {
    code: 'cy-gb-north',
    languageCode: 'cy',
    nameEn: 'North Welsh',
    nameNative: 'North Welsh',
    region: 'GB',
    cueTerms: ["diolch"],
    notes: 'Regional registry dialect for GB.',
  },
  {
    code: 'gd-gb-hebridean',
    languageCode: 'gd',
    nameEn: 'Hebridean Gaelic',
    nameNative: 'Hebridean Gaelic',
    region: 'GB',
    cueTerms: ["tapadh leat"],
    notes: 'Regional registry dialect for GB.',
  },
  {
    code: 'ga-ie-connacht',
    languageCode: 'ga',
    nameEn: 'Connacht Irish',
    nameNative: 'Connacht Irish',
    region: 'IE',
    cueTerms: ["go raibh maith agat"],
    notes: 'Regional registry dialect for IE.',
  },
  {
    code: 'qu-pe-cusco',
    languageCode: 'qu',
    nameEn: 'Cusco Quechua',
    nameNative: 'Cusco Quechua',
    region: 'PE',
    cueTerms: ["sulpayki"],
    notes: 'Regional registry dialect for PE.',
  },
  {
    code: 'gn-py-paraguayan',
    languageCode: 'gn',
    nameEn: 'Paraguayan Guarani',
    nameNative: 'Paraguayan Guarani',
    region: 'PY',
    cueTerms: ["aguyje"],
    notes: 'Regional registry dialect for PY.',
  },
  {
    code: 'ay-bo-central',
    languageCode: 'ay',
    nameEn: 'Central Aymara',
    nameNative: 'Central Aymara',
    region: 'BO',
    cueTerms: ["jukampi"],
    notes: 'Regional registry dialect for BO.',
  },
  {
    code: 'ht-ht-standard',
    languageCode: 'ht',
    nameEn: 'Standard Haitian Creole',
    nameNative: 'Standard Haitian Creole',
    region: 'HT',
    cueTerms: ["mesi"],
    notes: 'Regional registry dialect for HT.',
  },
  {
    code: 'nah-mx-central',
    languageCode: 'nah',
    nameEn: 'Central Nahuatl',
    nameNative: 'Central Nahuatl',
    region: 'MX',
    cueTerms: ["tlazohcamati"],
    notes: 'Regional registry dialect for MX.',
  },
  {
    code: 'chr-us-oklahoma',
    languageCode: 'chr',
    nameEn: 'Oklahoma Cherokee',
    nameNative: 'Oklahoma Cherokee',
    region: 'US',
    cueTerms: ["osiyo"],
    notes: 'Regional registry dialect for US.',
  },
  {
    code: 'nv-us-western',
    languageCode: 'nv',
    nameEn: 'Western Navajo',
    nameNative: 'Western Navajo',
    region: 'US',
    cueTerms: ["yaateeh"],
    notes: 'Regional registry dialect for US.',
  },
  {
    code: 'haw-us-standard',
    languageCode: 'haw',
    nameEn: 'Standard Hawaiian',
    nameNative: 'Standard Hawaiian',
    region: 'US',
    cueTerms: ["mahalo", "aloha"],
    notes: 'Regional registry dialect for US.',
  },
  {
    code: 'iu-ca-qikiqtaaluk',
    languageCode: 'iu',
    nameEn: 'South Qikiqtaaluk Inuktitut',
    nameNative: 'South Qikiqtaaluk Inuktitut',
    region: 'CA',
    cueTerms: ["nakurmiik"],
    notes: 'Regional registry dialect for CA.',
  },
  {
    code: 'fr-ca-quebecois',
    languageCode: 'fr',
    nameEn: 'Quebecois French',
    nameNative: 'Quebecois French',
    region: 'CA',
    cueTerms: ["bonjour"],
    notes: 'Regional registry dialect for CA.',
  },
  {
    code: 'hmn-us-white',
    languageCode: 'hmn',
    nameEn: 'White Hmong',
    nameNative: 'White Hmong',
    region: 'US',
    cueTerms: ["ua tsaug"],
    notes: 'Regional registry dialect for US.',
  }
];
