apiVersion: v1
kind: Service
metadata:
  name: verbalab-api
  namespace: verbalab
spec:
  selector:
    app: verbalab-api
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: verbalab-web
  namespace: verbalab
spec:
  selector:
    app: verbalab-web
  ports:
    - name: http
      port: 80
      targetPort: http
