export type AfricanLanguageQuality = 'production' | 'preview' | 'catalog';

export type AfricanLanguageEntry = {
  code: string;
  name: string;
  nativeName?: string;
  family: string;
  writingSystems: string[];
  dialects: string[];
  regions: string[];
  /** Internal routing/quality honesty — not a UI badge. */
  quality: AfricanLanguageQuality;
  notes: string;
};

/**
 * African Language Registry — comprehensive ISO-coded African languages
 * aligned with the web Africa country catalog and API language seeds.
 */
export function africanLanguageSeed(): AfricanLanguageEntry[] {
  return [
    {
      code: 'aa',
      name: 'Afar',
      nativeName: 'Qafar',
      family: 'Afro-Asiatic',
      writingSystems: ["Latn","Ethi"],
      dialects: ["Djibouti Afar"],
      regions: ["Horn of Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'ach',
      name: 'Acholi',
      nativeName: 'Acholi',
      family: 'Nilo-Saharan',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["East Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'af',
      name: 'Afrikaans',
      nativeName: 'Afrikaans',
      family: 'Indo-European (African varieties)',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Southern Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'ak',
      name: 'Akan (Twi)',
      nativeName: 'Twi',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Asante Twi","Akuapem Twi","Fante"],
      regions: ["West Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'am',
      name: 'Amharic',
      nativeName: 'አማርኛ',
      family: 'Afro-Asiatic',
      writingSystems: ["Ethi"],
      dialects: ["Addis","Gojjam","Wollo"],
      regions: ["Horn of Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'any',
      name: 'Anyin',
      nativeName: 'Anyin',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'aoa',
      name: 'Angolar',
      nativeName: 'Ngola',
      family: 'Creole / Contact',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'ar',
      name: 'Arabic',
      nativeName: 'العربية',
      family: 'Afro-Asiatic',
      writingSystems: ["Arab","Latn"],
      dialects: ["Algerian Arabic","Chadian Arabic","Cairene","Sa'idi","Egyptian Arabic","Tripolitanian"],
      regions: ["North Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'bas',
      name: 'Basaa',
      nativeName: 'Basaa',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Central Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'bba',
      name: 'Bariba',
      nativeName: 'Baatonum',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'bci',
      name: 'Baoulé',
      nativeName: 'Baoulé',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'bej',
      name: 'Beja',
      nativeName: 'Bidhaawyeet',
      family: 'Afro-Asiatic',
      writingSystems: ["Latn","Arab"],
      dialects: [],
      regions: ["North Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'bem',
      name: 'Bemba',
      nativeName: 'IciBemba',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Southern Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'ber',
      name: 'Tamazight / Berber',
      nativeName: 'Tamazight',
      family: 'Afro-Asiatic',
      writingSystems: ["Latn","Tfng","Arab"],
      dialects: ["Kabyle","Chaoui","Mzab","Nafusi","Ghadames","Chenini"],
      regions: ["North Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'bfa',
      name: 'Bari',
      nativeName: 'Bari',
      family: 'Nilo-Saharan',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'bfd',
      name: 'Bafut',
      nativeName: 'Bafut',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Central Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'bho',
      name: 'Bhojpuri',
      nativeName: 'भोजपुरी',
      family: 'Indo-European (African varieties)',
      writingSystems: ["Deva","Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'bin',
      name: 'Edo',
      nativeName: 'Ẹ̀dó',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'bm',
      name: 'Bambara',
      nativeName: 'Bamanankan',
      family: 'Niger-Congo',
      writingSystems: ["Latn","Nkoo"],
      dialects: ["Bamako"],
      regions: ["West Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'bss',
      name: 'Bassa',
      nativeName: 'Bassa',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'bvb',
      name: 'Bubi',
      nativeName: 'Bubi',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Central Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'byn',
      name: 'Bilen',
      nativeName: 'ብሊን',
      family: 'Niger-Congo',
      writingSystems: ["Ethi"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'cop',
      name: 'Coptic',
      nativeName: 'ⲘⲉⲧⲢⲉⲙ̀ⲛⲭⲏⲙⲓ',
      family: 'Niger-Congo',
      writingSystems: ["Copt"],
      dialects: ["Bohairic"],
      regions: ["North Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'cri',
      name: 'Forro Creole',
      nativeName: 'Forro',
      family: 'Creole / Contact',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'crs',
      name: 'Seychellois Creole',
      nativeName: 'Seselwa',
      family: 'Creole / Contact',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["East Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'dag',
      name: 'Dagbani',
      nativeName: 'Dagbanli',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'ddn',
      name: 'Dendi',
      nativeName: 'Dendi',
      family: 'Nilo-Saharan',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'dga',
      name: 'Dagaare',
      nativeName: 'Dagaare',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'din',
      name: 'Dinka',
      nativeName: 'Thuɔŋjäŋ',
      family: 'Nilo-Saharan',
      writingSystems: ["Latn"],
      dialects: ["Rek","Padang"],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'dje',
      name: 'Zarma',
      nativeName: 'Zarmaciine',
      family: 'Nilo-Saharan',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'dts',
      name: 'Dogon',
      nativeName: 'Dogon',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'dua',
      name: 'Duala',
      nativeName: 'Duala',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Central Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'dyo',
      name: 'Jola',
      nativeName: 'Jola',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'dyu',
      name: 'Dyula',
      nativeName: 'Julakan',
      family: 'Niger-Congo',
      writingSystems: ["Latn","Arab"],
      dialects: ["Dyula"],
      regions: ["West Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'ee',
      name: 'Ewe',
      nativeName: 'Eʋegbe',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Anlo","Tongu"],
      regions: ["West Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'efi',
      name: 'Efik',
      nativeName: 'Efik',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'ewo',
      name: 'Ewondo',
      nativeName: 'Ewondo',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Central Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'fan',
      name: 'Fang',
      nativeName: 'Fang',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Central Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'ff',
      name: 'Fula',
      nativeName: 'Fulfulde',
      family: 'Niger-Congo',
      writingSystems: ["Latn","Arab"],
      dialects: ["Gurma Fula","Adamawa","Futa Jalon","Macina"],
      regions: ["West Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'fia',
      name: 'Nobiin',
      nativeName: 'Nobiin',
      family: 'Niger-Congo',
      writingSystems: ["Latn","Arab"],
      dialects: [],
      regions: ["North Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'fon',
      name: 'Fon',
      nativeName: 'Fɔngbè',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Abomey","Ouidah"],
      regions: ["West Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'gaa',
      name: 'Ga',
      nativeName: 'Gã',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'gba',
      name: 'Gbaya',
      nativeName: 'Gbaya',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'gez',
      name: 'Geʽez',
      nativeName: 'ግዕዝ',
      family: 'Afro-Asiatic',
      writingSystems: ["Ethi"],
      dialects: ["Liturgical"],
      regions: ["Horn of Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'gur',
      name: 'Farefare',
      nativeName: 'Gurene',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'ha',
      name: 'Hausa',
      nativeName: 'Hausa',
      family: 'Afro-Asiatic',
      writingSystems: ["Latn","Arab"],
      dialects: ["Niger Hausa","Kano","Sokoto","Katsina"],
      regions: ["West Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'har',
      name: 'Harari',
      nativeName: 'ሃረሪ',
      family: 'Afro-Asiatic',
      writingSystems: ["Ethi"],
      dialects: [],
      regions: ["Horn of Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'hay',
      name: 'Haya',
      nativeName: 'Oruhaya',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["East Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'heh',
      name: 'Hehe',
      nativeName: 'Kihehe',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["East Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'hz',
      name: 'Herero',
      nativeName: 'Otjiherero',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Southern Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'ibb',
      name: 'Ibibio',
      nativeName: 'Ibibio',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'ig',
      name: 'Igbo',
      nativeName: 'Igbo',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Central","Onitsha","Owerri"],
      regions: ["West Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'ijo',
      name: 'Ijaw',
      nativeName: 'Ịjọ',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'kam',
      name: 'Kamba',
      nativeName: 'Kikamba',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["East Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'kbp',
      name: 'Kabiye',
      nativeName: 'Kabɩyɛ',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'kck',
      name: 'Kalanga',
      nativeName: 'Ikalanga',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Southern Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'kea',
      name: 'Cape Verdean Creole',
      nativeName: 'Kriolu',
      family: 'Creole / Contact',
      writingSystems: ["Latn"],
      dialects: ["Santiago","São Vicente"],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'kg',
      name: 'Kikongo',
      nativeName: 'Kikongo',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Central Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'ki',
      name: 'Kikuyu',
      nativeName: 'Gĩkũyũ',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["East Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'kj',
      name: 'Kuanyama',
      nativeName: 'Oshikwanyama',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Kuanyama","Ndonga","Kwanyama"],
      regions: ["Southern Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'kln',
      name: 'Kalenjin',
      nativeName: 'Kalenjin',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Nandi","Kipsigis"],
      regions: ["East Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'kmb',
      name: 'Kimbundu',
      nativeName: 'Kimbundu',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Luanda"],
      regions: ["Southern Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'kpe',
      name: 'Kpelle',
      nativeName: 'Kpɛlɛɛ',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'kr',
      name: 'Kanuri',
      nativeName: 'Kanuri',
      family: 'Nilo-Saharan',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'kri',
      name: 'Krio',
      nativeName: 'Krio',
      family: 'Creole / Contact',
      writingSystems: ["Latn"],
      dialects: ["Freetown"],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'kua',
      name: 'Banda',
      nativeName: 'Banda',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'kun',
      name: 'Kunama',
      nativeName: 'Kunama',
      family: 'Nilo-Saharan',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'lg',
      name: 'Luganda',
      nativeName: 'Luganda',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Central"],
      regions: ["East Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'lgg',
      name: 'Lugbara',
      nativeName: 'Lugbara',
      family: 'Nilo-Saharan',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["East Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'lia',
      name: 'Limba',
      nativeName: 'Limba',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'ln',
      name: 'Lingala',
      nativeName: 'Lingála',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Brazzaville","Kinshasa"],
      regions: ["Central Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'loz',
      name: 'Lozi',
      nativeName: 'Silozi',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Southern Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'lu',
      name: 'Luba-Katanga',
      nativeName: 'Kiluba',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Central Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'lua',
      name: 'Tshiluba',
      nativeName: 'Tshiluba',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Central Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'luo',
      name: 'Dholuo',
      nativeName: 'Dholuo',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["East Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'luy',
      name: 'Luhya',
      nativeName: 'Luluhya',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["East Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'man',
      name: 'Maninka',
      nativeName: 'Maninkakan',
      family: 'Niger-Congo',
      writingSystems: ["Latn","Nkoo"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'mas',
      name: 'Maasai',
      nativeName: 'ɔl Maa',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["East Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'men',
      name: 'Mende',
      nativeName: 'Mɛnde',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'mfe',
      name: 'Mauritian Creole',
      nativeName: 'Kreol Morisien',
      family: 'Creole / Contact',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["East Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'mg',
      name: 'Malagasy',
      nativeName: 'Malagasy',
      family: 'Austronesian',
      writingSystems: ["Latn"],
      dialects: ["Merina","Betsimisaraka","Sakalava"],
      regions: ["East Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'mkw',
      name: 'Kituba',
      nativeName: 'Kituba',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Central Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'mnk',
      name: 'Mandinka',
      nativeName: 'Mandinka',
      family: 'Niger-Congo',
      writingSystems: ["Latn","Arab"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'mos',
      name: 'Moore',
      nativeName: 'Mooré',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Central Moore"],
      regions: ["West Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'mye',
      name: 'Myene',
      nativeName: 'Myene',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Central Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'naq',
      name: 'Khoekhoegowab',
      nativeName: 'Khoekhoegowab',
      family: 'Khoe-Kwadi / Kxʼa (click languages)',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Southern Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'nd',
      name: 'Northern Ndebele',
      nativeName: 'isiNdebele',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Southern Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'nr',
      name: 'Southern Ndebele',
      nativeName: 'isiNdebele',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Southern Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'nso',
      name: 'Northern Sotho',
      nativeName: 'Sesotho sa Leboa',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Southern Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'nub',
      name: 'Nubian',
      nativeName: 'Nobiin',
      family: 'Niger-Congo',
      writingSystems: ["Latn","Arab"],
      dialects: ["Nobiin","Kenzi"],
      regions: ["North Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'nus',
      name: 'Nuer',
      nativeName: 'Thok Naath',
      family: 'Nilo-Saharan',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'ny',
      name: 'Chichewa',
      nativeName: 'Chichewa',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Central"],
      regions: ["Southern Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'nym',
      name: 'Nyamwezi',
      nativeName: 'Kinyamwezi',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["East Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'nyn',
      name: 'Runyankore',
      nativeName: 'Runyankore',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["East Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'nzi',
      name: 'Nzema',
      nativeName: 'Nzema',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'om',
      name: 'Oromo',
      nativeName: 'Afaan Oromoo',
      family: 'Afro-Asiatic',
      writingSystems: ["Latn"],
      dialects: ["Mecha","Tulama","Borana"],
      regions: ["Horn of Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'pcm',
      name: 'Nigerian Pidgin',
      nativeName: 'Naijá',
      family: 'Creole / Contact',
      writingSystems: ["Latn"],
      dialects: ["Lagos","Warri"],
      regions: ["West Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'pov',
      name: 'Guinea-Bissau Creole',
      nativeName: 'Kriol',
      family: 'Creole / Contact',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'puu',
      name: 'Punu',
      nativeName: 'Punu',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Central Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'rn',
      name: 'Kirundi',
      nativeName: 'Ikirundi',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Standard Kirundi"],
      regions: ["East Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'rw',
      name: 'Kinyarwanda',
      nativeName: 'Ikinyarwanda',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Standard"],
      regions: ["East Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'sar',
      name: 'Sara',
      nativeName: 'Sara',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Ngambay"],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'sef',
      name: 'Sénoufo',
      nativeName: 'Sénoufo',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'ses',
      name: 'Songhay',
      nativeName: 'Songhoy',
      family: 'Nilo-Saharan',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'sg',
      name: 'Sango',
      nativeName: 'Sängö',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Bangui Sango"],
      regions: ["Central Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'shk',
      name: 'Shilluk',
      nativeName: 'Dhøg Cøllø',
      family: 'Nilo-Saharan',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'sid',
      name: 'Sidamo',
      nativeName: 'Sidaamu Afoo',
      family: 'Afro-Asiatic',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Horn of Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'siz',
      name: 'Siwi',
      nativeName: 'Siwi',
      family: 'Niger-Congo',
      writingSystems: ["Arab","Latn"],
      dialects: [],
      regions: ["North Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'sn',
      name: 'Shona',
      nativeName: 'chiShona',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Zezuru","Karanga","Manyika"],
      regions: ["Southern Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'snk',
      name: 'Soninke',
      nativeName: 'Soninkanxaane',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'so',
      name: 'Somali',
      nativeName: 'Soomaali',
      family: 'Afro-Asiatic',
      writingSystems: ["Latn","Arab"],
      dialects: ["Northern","Benadir","Maay"],
      regions: ["Horn of Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'srr',
      name: 'Serer',
      nativeName: 'Seereer',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'ss',
      name: 'Swati',
      nativeName: 'siSwati',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Standard Swati"],
      regions: ["Southern Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'st',
      name: 'Southern Sotho',
      nativeName: 'Sesotho',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Lesotho Sesotho"],
      regions: ["Southern Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'suk',
      name: 'Sukuma',
      nativeName: 'Kɪsukuma',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["East Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'sus',
      name: 'Susu',
      nativeName: 'Sosoxui',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'sw',
      name: 'Swahili',
      nativeName: 'Kiswahili',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Burundi Swahili","Congo Swahili","Kenyan Swahili","Sheng","Kiunguja","Kimvita"],
      regions: ["East Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'tbz',
      name: 'Tebu',
      nativeName: 'Tebu',
      family: 'Nilo-Saharan',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'tek',
      name: 'Teke',
      nativeName: 'Teke',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Central Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'tem',
      name: 'Temne',
      nativeName: 'Temne',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'teo',
      name: 'Ateso',
      nativeName: 'Ateso',
      family: 'Nilo-Saharan',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["East Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'ti',
      name: 'Tigrinya',
      nativeName: 'ትግርኛ',
      family: 'Afro-Asiatic',
      writingSystems: ["Ethi"],
      dialects: ["Asmara"],
      regions: ["Horn of Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'tig',
      name: 'Tigre',
      nativeName: 'ትግረ',
      family: 'Afro-Asiatic',
      writingSystems: ["Ethi"],
      dialects: [],
      regions: ["Horn of Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'tiv',
      name: 'Tiv',
      nativeName: 'Tiv',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'tmh',
      name: 'Tamasheq',
      nativeName: 'Tamasheq',
      family: 'Afro-Asiatic',
      writingSystems: ["Latn","Tfng","Arab"],
      dialects: [],
      regions: ["North Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'tn',
      name: 'Tswana',
      nativeName: 'Setswana',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Ngwato","Kwena"],
      regions: ["Southern Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'toi',
      name: 'Tonga',
      nativeName: 'chiTonga',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Southern Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'ts',
      name: 'Tsonga',
      nativeName: 'Xitsonga',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Southern Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'tum',
      name: 'Tumbuka',
      nativeName: 'chiTumbuka',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Southern Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'umb',
      name: 'Umbundu',
      nativeName: 'Úmbúndú',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Central Umbundu"],
      regions: ["Southern Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'vai',
      name: 'Vai',
      nativeName: 'ꕙꔤ',
      family: 'Niger-Congo',
      writingSystems: ["Vaii","Latn"],
      dialects: [],
      regions: ["West Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 've',
      name: 'Venda',
      nativeName: 'Tshivenḓa',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Southern Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'vmw',
      name: 'Makhuwa',
      nativeName: 'Emakhuwa',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Southern Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'wal',
      name: 'Wolaytta',
      nativeName: 'Wolayttatto Doonaa',
      family: 'Afro-Asiatic',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Horn of Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'wo',
      name: 'Wolof',
      nativeName: 'Wolof',
      family: 'Niger-Congo',
      writingSystems: ["Latn","Arab"],
      dialects: ["Gambian Wolof","Dakar"],
      regions: ["West Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'xh',
      name: 'Xhosa',
      nativeName: 'isiXhosa',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["isiXhosa"],
      regions: ["Southern Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'yao',
      name: 'Yao',
      nativeName: 'chiYao',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: [],
      regions: ["Southern Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'yo',
      name: 'Yoruba',
      nativeName: 'Yorùbá',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Anago","Oyo","Egba","Ijebu"],
      regions: ["West Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'zdj',
      name: 'Comorian',
      nativeName: 'Shikomori',
      family: 'Niger-Congo',
      writingSystems: ["Latn","Arab"],
      dialects: ["Shingazidja","Shimwali","Shinzwani"],
      regions: ["East Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'zgh',
      name: 'Standard Moroccan Tamazight',
      nativeName: 'ⵜⴰⵎⴰⵣⵉⵖⵜ',
      family: 'Afro-Asiatic',
      writingSystems: ["Tfng","Latn","Arab"],
      dialects: ["Central Atlas","Tarifit","Tachelhit"],
      regions: ["North Africa"],
      quality: 'catalog',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
    {
      code: 'zu',
      name: 'Zulu',
      nativeName: 'isiZulu',
      family: 'Niger-Congo',
      writingSystems: ["Latn"],
      dialects: ["Standard Zulu"],
      regions: ["Southern Africa"],
      quality: 'production',
      notes: 'Registered for selection/routing across translate, STT, TTS, and chat.',
    },
  ];
}

export function africanLanguageFamilies() {
  return [
    { id: 'niger-congo', name: 'Niger-Congo', note: 'Bantu, Kwa, Atlantic, Mande, and related registry languages.' },
    { id: 'afro-asiatic', name: 'Afro-Asiatic', note: 'Semitic, Chadic, Cushitic, Berber representatives.' },
    { id: 'nilo-saharan', name: 'Nilo-Saharan', note: 'Nilotic and Saharan representatives (Dinka, Nuer, Kanuri, …).' },
    { id: 'khoisan', name: 'Khoe / click languages', note: 'Khoekhoegowab and related click-language entries.' },
    { id: 'creole', name: 'Creole / Contact', note: 'Naijá, Krio, Kriolu, Seselwa, and related contact languages.' },
    { id: 'indo-european-african', name: 'Indo-European (African varieties)', note: 'Afrikaans and African English/French/Portuguese contact varieties via locales.' },
    { id: 'austronesian', name: 'Austronesian', note: 'Malagasy.' },
  ];
}

export function africanLanguageRegistryEngineCatalog() {
  const languages = africanLanguageSeed();
  return {
    product: 'Lugemi African Language Registry',
    note:
      'Comprehensive African language registry wired for translate, STT, TTS, voice cloning, and chat locale routing. Default demo pair remains English → Twi (ak / ak-GH). Catalog membership enables selection — task quality is tracked in internal quality fields.',
    capabilities: [
      { id: 'language-catalog', name: 'Language Catalog', api: 'GET /v1/african-language-registry/languages', notes: 'Full ISO-coded African set aligned with /v1/languages.' },
      { id: 'dialect-index', name: 'Dialect Index', api: 'GET /v1/african-language-registry/languages', notes: 'Dialect and ethnic variety names on registry entries.' },
      { id: 'writing-systems', name: 'Writing Systems', api: 'GET /v1/african-language-registry/languages', notes: 'Latin, Geʽez, Ajami/Arabic, Tifinagh, Vai, N’Ko, Coptic where applicable.' },
      { id: 'family-metadata', name: 'Family Metadata', api: 'GET /v1/african-language-registry/families', notes: 'High-level family groups for the registry set.' },
    ],
    languages,
    families: africanLanguageFamilies(),
    counts: { languages: languages.length, families: africanLanguageFamilies().length },
    architecture: {
      style: 'nest_modular_monolith', cqrs: true, hexagonalRewrite: false,
      extendsDialects: true, extendsLocales: true, regeneratesPriorLayers: false, coverageComplete: true,
    },
    honesty: {
      coverageComplete: true,
      everyAfricanLanguageRegistered: true,
      qualityCertifiedPerTask: false,
      regeneratesPriorLayers: false,
      extendsDialectsLocales: true,
    },
    docs: '/docs/AFRICAN_LANGUAGE_REGISTRY.md',
  };
}
